import type { Deal, MarketSignal, PlatformStats } from '@/types'

export const mockDeals: Deal[] = [
  {
    id: 'deal-001',
    projectName: 'Gulf Coast Cold Storage Campus',
    location: 'New Orleans, LA',
    projectType: 'cold_storage',
    sponsor: 'Gulf Logistics Development LLC',
    stage: 'capital_ready',
    technology: 'Microgrid + Battery Storage',
    infrastructureType: 'Cold Storage + Energy Infrastructure',
    capitalRequirement: 48000000,
    createdAt: '2024-11-01',
    updatedAt: '2024-12-15',
    documents: [
      { id: 'd1', name: 'Feasibility_Study_GCCS.pdf', type: 'feasibility', uploadedAt: '2024-11-01', size: '4.2 MB', processed: true },
      { id: 'd2', name: 'Financial_Model_v3.xlsx', type: 'financial', uploadedAt: '2024-11-08', size: '1.8 MB', processed: true },
      { id: 'd3', name: 'Site_Plan_Phase1.dwg', type: 'architectural', uploadedAt: '2024-11-15', size: '12.4 MB', processed: true },
      { id: 'd4', name: 'Energy_Model_Microgrid.pdf', type: 'engineering', uploadedAt: '2024-11-22', size: '3.1 MB', processed: true },
    ],
    dna: {
      sector: 'Cold Storage',
      technology: ['microgrid', 'battery_storage'],
      capitalStack: ['Opportunity Zone', 'infrastructure_debt', 'tax_credits'],
      geography: 'Gulf Coast OZ',
      ozEligible: true,
    },
    bdcScore: {
      projectViability: 84,
      marketStrength: 79,
      capitalReadiness: 91,
      technologyIntegration: 88,
      strategicAlignment: 82,
      overall: 85,
    },
    capitalStack: {
      equity: 14400000,
      debt: 28800000,
      incentives: 4800000,
      totalCapital: 48000000,
      debtStructure: ['Construction Financing', 'Infrastructure Debt'],
      incentiveTypes: ['Opportunity Zone Equity', 'ITC Tax Credit'],
      investorTypes: ['Family Office', 'Impact Investor', 'Infrastructure Fund'],
    },
    correlations: [
      { dealId: 'deal-002', dealName: 'Louisiana Renewable Energy Campus', overlapType: 'Energy Infrastructure', strength: 0.91, opportunity: 'Shared microgrid backbone — potential 18% cost reduction' },
      { dealId: 'deal-003', dealName: 'Mississippi Agriculture Platform', overlapType: 'Cold Chain Logistics', strength: 0.74, opportunity: 'Integrated cold chain serving regional food distribution' },
    ],
    platformDistribution: ['BDC', 'GDG', 'RRG', 'EnerGenius'],
    riskIndicators: ['Grid interconnection timeline 9-12 months', 'Permitting complexity in coastal zone'],
    strategicNextSteps: ['Commission lender package', 'Initiate OZ equity raise', 'Engage RRG for microgrid design', 'Confirm site control'],
    marketProfile: {
      demand: 'Strong — food logistics demand growing 14% YoY in Gulf region',
      sectorGrowth: 'Cold storage vacancy below 3% in target market',
      regionalIndicators: 'Port of New Orleans expansion driving logistics demand',
    },
  },
  {
    id: 'deal-002',
    projectName: 'Louisiana Renewable Energy Campus',
    location: 'Baton Rouge, LA',
    projectType: 'energy_campus',
    sponsor: 'RRG Development Partners',
    stage: 'structurable',
    technology: 'Solar + Battery + SmartConnect',
    infrastructureType: 'Power Generation + Grid Services',
    capitalRequirement: 72000000,
    createdAt: '2024-10-15',
    updatedAt: '2024-12-10',
    documents: [
      { id: 'd5', name: 'Energy_Feasibility_LA.pdf', type: 'feasibility', uploadedAt: '2024-10-15', size: '5.8 MB', processed: true },
      { id: 'd6', name: 'Interconnection_Study.pdf', type: 'engineering', uploadedAt: '2024-10-28', size: '2.3 MB', processed: true },
      { id: 'd7', name: 'Investor_Deck_v2.pptx', type: 'financial', uploadedAt: '2024-11-05', size: '8.7 MB', processed: false },
    ],
    dna: {
      sector: 'Energy',
      technology: ['microgrid', 'battery_storage', 'smart_connect'],
      capitalStack: ['infrastructure_debt', 'tax_credits', 'equity'],
      geography: 'Southeast US',
      ozEligible: false,
    },
    bdcScore: {
      projectViability: 78,
      marketStrength: 85,
      capitalReadiness: 69,
      technologyIntegration: 94,
      strategicAlignment: 88,
      overall: 83,
    },
    capitalStack: {
      equity: 18000000,
      debt: 46800000,
      incentives: 7200000,
      totalCapital: 72000000,
      debtStructure: ['Project Finance', 'Infrastructure Debt'],
      incentiveTypes: ['ITC', 'USDA Grant', 'State Incentives'],
      investorTypes: ['Climate Fund', 'Infrastructure Fund'],
    },
    correlations: [
      { dealId: 'deal-001', dealName: 'Gulf Coast Cold Storage Campus', overlapType: 'Energy Infrastructure', strength: 0.91, opportunity: 'Power purchase agreement potential for GCCS facility' },
      { dealId: 'deal-004', dealName: 'Digital Infrastructure Campus TX', overlapType: 'Power Supply', strength: 0.68, opportunity: 'Anchor offtaker for energy campus output' },
    ],
    platformDistribution: ['BDC', 'RRG', 'EnerGenius'],
    riskIndicators: ['ITC recapture risk if sold within 5 years', 'Interconnection queue delays in MISO territory'],
    strategicNextSteps: ['Complete capital stack modeling', 'Identify anchor offtake agreement', 'Engage climate fund investors', 'RRG microgrid design finalization'],
    marketProfile: {
      demand: 'High — industrial energy demand growing with reshoring trend',
      sectorGrowth: 'Renewable capacity additions accelerating, 23% YoY',
      regionalIndicators: 'Louisiana industrial corridor expansion, $4.2B committed capex',
    },
  },
  {
    id: 'deal-003',
    projectName: 'Mississippi Smart Agriculture Platform',
    location: 'Jackson, MS',
    projectType: 'agriculture',
    sponsor: 'Agri-Tech Development Group',
    stage: 'early_stage',
    technology: 'Vertical Farming + SmartConnect',
    infrastructureType: 'Controlled Environment Agriculture',
    capitalRequirement: 31000000,
    createdAt: '2024-12-01',
    updatedAt: '2024-12-18',
    documents: [
      { id: 'd8', name: 'Market_Analysis_AgTech.pdf', type: 'market', uploadedAt: '2024-12-01', size: '3.4 MB', processed: true },
      { id: 'd9', name: 'Site_Control_Letter_Jackson.pdf', type: 'site_control', uploadedAt: '2024-12-08', size: '0.8 MB', processed: true },
    ],
    dna: {
      sector: 'Agriculture',
      technology: ['vertical_farming', 'smart_connect'],
      capitalStack: ['NMTC', 'Opportunity Zone', 'equity'],
      geography: 'Rural OZ Mississippi',
      ozEligible: true,
    },
    bdcScore: {
      projectViability: 71,
      marketStrength: 68,
      capitalReadiness: 58,
      technologyIntegration: 77,
      strategicAlignment: 75,
      overall: 70,
    },
    capitalStack: {
      equity: 9300000,
      debt: 16750000,
      incentives: 4950000,
      totalCapital: 31000000,
      debtStructure: ['NMTC Allocation', 'USDA Rural Development'],
      incentiveTypes: ['New Markets Tax Credit', 'Opportunity Zone', 'USDA Grant'],
      investorTypes: ['Impact Investor', 'CDFI', 'Family Office'],
    },
    correlations: [
      { dealId: 'deal-001', dealName: 'Gulf Coast Cold Storage Campus', overlapType: 'Cold Chain Integration', strength: 0.74, opportunity: 'Agricultural output cold storage — direct revenue link' },
    ],
    platformDistribution: ['BDC', 'GDG'],
    riskIndicators: ['Early stage — site control not finalized', 'Technology unproven at scale in region', 'NMTC allocation competitive process'],
    strategicNextSteps: ['Secure site control', 'Commission feasibility study', 'Identify NMTC allocatee', 'Develop pilot program plan'],
    marketProfile: {
      demand: 'Growing — food security investment increasing post-supply chain disruptions',
      sectorGrowth: 'Controlled environment agriculture 31% CAGR projected through 2028',
      regionalIndicators: 'Mississippi Delta food production corridor, federal investment active',
    },
  },
  {
    id: 'deal-004',
    projectName: 'Texas Digital Infrastructure Campus',
    location: 'Houston, TX',
    projectType: 'digital_infrastructure',
    sponsor: 'DataCore Development LLC',
    stage: 'lender_ready',
    technology: 'Data Center + Microgrid + Battery',
    infrastructureType: 'Digital Infrastructure + Power',
    capitalRequirement: 125000000,
    createdAt: '2024-09-01',
    updatedAt: '2024-12-20',
    documents: [
      { id: 'd10', name: 'Full_Feasibility_TDIC.pdf', type: 'feasibility', uploadedAt: '2024-09-01', size: '7.2 MB', processed: true },
      { id: 'd11', name: 'Lender_Package_v4.pdf', type: 'financial', uploadedAt: '2024-11-15', size: '15.3 MB', processed: true },
      { id: 'd12', name: 'Engineering_Report_Final.pdf', type: 'engineering', uploadedAt: '2024-10-01', size: '9.8 MB', processed: true },
      { id: 'd13', name: 'Site_Plan_Approved.dwg', type: 'architectural', uploadedAt: '2024-10-15', size: '22.1 MB', processed: true },
      { id: 'd14', name: 'Environmental_Assessment.pdf', type: 'engineering', uploadedAt: '2024-10-30', size: '4.5 MB', processed: true },
    ],
    dna: {
      sector: 'Digital Infrastructure',
      technology: ['microgrid', 'battery_storage', 'smart_connect'],
      capitalStack: ['infrastructure_debt', 'equity', 'tax_credits'],
      geography: 'Texas Energy Corridor',
      ozEligible: false,
    },
    bdcScore: {
      projectViability: 93,
      marketStrength: 91,
      capitalReadiness: 96,
      technologyIntegration: 92,
      strategicAlignment: 87,
      overall: 92,
    },
    capitalStack: {
      equity: 37500000,
      debt: 81250000,
      incentives: 6250000,
      totalCapital: 125000000,
      debtStructure: ['Senior Construction Loan', 'Infrastructure Term Debt', 'Mezzanine'],
      incentiveTypes: ['ITC', 'Texas Enterprise Zone', 'Federal CHIPS Act'],
      investorTypes: ['Infrastructure Fund', 'Pension Fund', 'Sovereign Wealth'],
    },
    correlations: [
      { dealId: 'deal-002', dealName: 'Louisiana Renewable Energy Campus', overlapType: 'Power Supply', strength: 0.68, opportunity: 'Long-term PPA to anchor Louisiana energy project' },
    ],
    platformDistribution: ['BDC', 'GDG', 'RRG', 'EnerGenius'],
    riskIndicators: ['Grid reliability in ERCOT', 'Data center market saturation risk in Houston by 2027'],
    strategicNextSteps: ['Close construction financing', 'Execute PPA with energy campus', 'Initiate site work', 'SmartConnect integration planning'],
    marketProfile: {
      demand: 'Exceptional — AI compute demand driving 40%+ data center growth YoY',
      sectorGrowth: 'Texas data center market projected to triple by 2028',
      regionalIndicators: 'Houston Energy Corridor attracting $18B+ infrastructure investment',
    },
  },
  {
    id: 'deal-005',
    projectName: 'Ohio Waste-to-Energy Facility',
    location: 'Columbus, OH',
    projectType: 'waste_to_energy',
    sponsor: 'Midwest Energy Solutions',
    stage: 'structurable',
    technology: 'WTE Conversion + Microgrid',
    infrastructureType: 'Waste Processing + Power Generation',
    capitalRequirement: 58000000,
    createdAt: '2024-11-20',
    updatedAt: '2024-12-19',
    documents: [
      { id: 'd15', name: 'WTE_Feasibility_Ohio.pdf', type: 'feasibility', uploadedAt: '2024-11-20', size: '6.1 MB', processed: true },
      { id: 'd16', name: 'Environmental_Impact_Study.pdf', type: 'engineering', uploadedAt: '2024-12-01', size: '8.4 MB', processed: false },
      { id: 'd17', name: 'Financial_Model_WTE.xlsx', type: 'financial', uploadedAt: '2024-12-10', size: '2.2 MB', processed: true },
    ],
    dna: {
      sector: 'Waste-to-Energy',
      technology: ['waste_to_energy', 'microgrid'],
      capitalStack: ['infrastructure_debt', 'equity', 'grant'],
      geography: 'Midwest Urban',
      ozEligible: false,
    },
    bdcScore: {
      projectViability: 76,
      marketStrength: 72,
      capitalReadiness: 65,
      technologyIntegration: 83,
      strategicAlignment: 79,
      overall: 75,
    },
    capitalStack: {
      equity: 17400000,
      debt: 34800000,
      incentives: 5800000,
      totalCapital: 58000000,
      debtStructure: ['Green Infrastructure Debt', 'Municipal Bond'],
      incentiveTypes: ['EPA Grant', 'State Energy Incentive', 'Tipping Fee Revenue'],
      investorTypes: ['Municipal Authority', 'Climate Fund', 'Infrastructure Fund'],
    },
    correlations: [],
    platformDistribution: ['BDC', 'GDG', 'RRG'],
    riskIndicators: ['Environmental permitting 18-24 month timeline', 'Community opposition risk', 'Technology vendor dependency'],
    strategicNextSteps: ['Complete environmental impact study', 'Engage municipal stakeholders', 'Identify EPA grant program', 'Capital stack finalization'],
    marketProfile: {
      demand: 'Moderate — municipal waste processing demand stable, energy offtake critical',
      sectorGrowth: 'WTE sector growing 8% annually driven by landfill restrictions',
      regionalIndicators: 'Columbus Smart City Initiative creating favorable regulatory environment',
    },
  },
]

export const mockMarketSignals: MarketSignal[] = [
  {
    id: 'sig-001',
    sector: 'Cold Storage Infrastructure',
    region: 'Gulf Coast',
    signal: 'Emerging Opportunity Detected',
    strength: 'high',
    drivers: ['Food logistics demand up 14% YoY', 'Grid instability driving backup power investment', 'Agriculture export growth from Mississippi Delta'],
    recommendation: 'Cold storage + microgrid integration — 84% match with successful infrastructure typology',
    detectedAt: '2024-12-20',
  },
  {
    id: 'sig-002',
    sector: 'Digital Infrastructure',
    region: 'Texas / Southwest',
    signal: 'Capital Flow Surge Detected',
    strength: 'high',
    drivers: ['AI compute demand accelerating', 'CHIPS Act funding deployment', 'Power-hungry workloads requiring on-site generation'],
    recommendation: 'Data center + renewable energy campus pairing — high ROI structure',
    detectedAt: '2024-12-18',
  },
  {
    id: 'sig-003',
    sector: 'Renewable Energy',
    region: 'Southeast US',
    signal: 'Infrastructure Gap Identified',
    strength: 'medium',
    drivers: ['Industrial reshoring creating energy demand', 'Grid capacity constraints', 'Carbon incentive expansion'],
    recommendation: 'Distributed microgrid + battery deployment — structurable with ITC stack',
    detectedAt: '2024-12-15',
  },
]

export const mockStats: PlatformStats = {
  totalDeals: 5,
  totalCapital: 334000000,
  avgBdcScore: 81,
  dealsByStage: {
    early_stage: 1,
    structurable: 2,
    capital_ready: 1,
    lender_ready: 1,
  },
  dealsByType: {
    cold_storage: 1,
    energy_campus: 1,
    agriculture: 1,
    digital_infrastructure: 1,
    waste_to_energy: 1,
  },
  capitalByPlatform: {
    BDC: 334000000,
    GDG: 262000000,
    RRG: 178000000,
    EnerGenius: 245000000,
  },
}
